[pytest]
pythonpath = .
addopts = --cov=./api --cov-report=json --import-mode=importlib --cov-branch --cov-report=xml
env =
    ANTHROPIC_API_KEY = <mock-anthropic-api-key>
    AZURE_OPENAI_API_BASE = https://difyai-openai.openai.azure.com
    AZURE_OPENAI_API_KEY = <mock-azure-openai-api-key>
    CHATGLM_API_BASE = http://a.abc.com:11451
    CODE_EXECUTION_API_KEY = <mock-code-execution-api-key>
    CODE_EXECUTION_ENDPOINT = http://127.0.0.1:8194
    CODE_MAX_STRING_LENGTH = 400000
    PLUGIN_DAEMON_KEY = <mock-plugin-daemon-key>
    PLUGIN_DAEMON_URL = http://127.0.0.1:5002
    PLUGIN_MAX_PACKAGE_SIZE = 15728640
    INNER_API_KEY_FOR_PLUGIN = <mock-inner-api-key-for-plugin>
    MARKETPLACE_ENABLED = true
    MARKETPLACE_API_URL = https://marketplace.dify.ai
    FIRECRAWL_API_KEY = <mock-firecrawl-api-key>
    FIREWORKS_API_KEY = <mock-fireworks-api-key>
    GOOGLE_API_KEY = <mock-google-api-key>
    HUGGINGFACE_API_KEY = <mock-huggingface-api-key>
    HUGGINGFACE_EMBEDDINGS_ENDPOINT_URL = c
    HUGGINGFACE_TEXT2TEXT_GEN_ENDPOINT_URL = b
    HUGGINGFACE_TEXT_GEN_ENDPOINT_URL = a
    MIXEDBREAD_API_KEY = <mock-mixedbread-api-key>
    MOCK_SWITCH = true
    NOMIC_API_KEY = <mock-nomic-api-key>
    OPENAI_API_KEY = <mock-openai-api-key>
    TEI_EMBEDDING_SERVER_URL = http://a.abc.com:11451
    TEI_RERANK_SERVER_URL = http://a.abc.com:11451
    TEI_API_KEY = <mock-tei-api-key>
    UPSTAGE_API_KEY = <mock-upstage-api-key>
    VOYAGE_API_KEY = <mock-voyage-api-key>
    XINFERENCE_CHAT_MODEL_UID = chat
    XINFERENCE_EMBEDDINGS_MODEL_UID = embedding
    XINFERENCE_GENERATION_MODEL_UID = generate
    XINFERENCE_RERANK_MODEL_UID = rerank
    XINFERENCE_SERVER_URL = http://a.abc.com:11451
    GITEE_AI_API_KEY = <mock-gitee-ai-api-key>
